### PR TITLE
Accepting different avatar components than Avatar.Image

### PR DESCRIPTION
**Pull request by mariohmol**
Nowadays its possible to include an option avatar just with a Avatar.Image.

Would be great if the sourceAvatar could accept any component, so it can inject an Avatar.Icon or any other that he might to.

Based on request: #20

In sake of keeping the existing docs and code correct, I did create a new property
```js
{
    value: '1',
    label: 'Tiger Nixon',
    employee_salary: '320800',
    employee_age: '61',
    avatarComponent: <Avatar.Icon size={24} icon="folder" />,
  },
```

Thanks!

### CODE REVIEW

**Comment by srk-sharingan** [comment]
Did you try executing the changes in the simulator? Because I don't get the Icon when I added it. Also, avatarComponent props can not be  **FC**.

**Comment by srk-sharingan** [comment]
Also, the check condition on the item seems to be incorrect, 
`  {enableAvatar && avatarComponent ? (
            avatarComponent
          ) : (
            <Avatar.Image
              size={avatarSize}
              style={styles.avatarView}
              source={avatarSource || defaultAvatar}
            />
          )}`

If I don't pass the **enableAvatar** prop, It should not set the avatar but the above condition will set the default image avatar as the item avatar when the **enableAvatar** prop is not given.

**Comment by mariohmol** [comment]
Yes.. now I realized.. the problem was the linter.. when I did commit he asked me to remove the parentesis

**Comment by mariohmol** [comment]
Ok, I did submit a change that fits the linter and the logic

**Comment by mariohmol** [comment]
> avatarComponent

why it cant? what it should be instead?

**Comment by srk-sharingan** [comment]
The avatar prop from the Chip expects the ReactNode, here I need the component with the signature of children. So **FC** isn't the correct prop to use.
Screenshot 2021-03-04 at 8 57 20 AM

**Comment by mariohmol** [comment]
So what we should use as a type here? kind lost

**Comment by srk-sharingan** [comment]
ReactNode should work.

**Comment by mariohmol** [comment]
awesome.. thank you! pushed the change!

**Comment by mariohmol** [comment]
Hi, when u can please release a version with this.. would be awesome to incorporate the icons on the dropdown =)

**Comment by srk-sharingan** [comment]
I am planning to do it tomorrow(Saturday). Since I am little engaged with other work. Also, I need to do a quick test for this, all of this will take quite a lot of time.

**Comment by mariohmol** [comment]
You rock!!

**Pull request merged**
